version: '3.10'

services:
  db:
    image: postgres:latest
    env_file:
      - .env
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - '${DB_PORT}:5432'

  app:
    build: .
    ports:
      - '8000:8000'
    restart: "always"
    env_file:
      - .env
    command: >
      sh -c 'cd ./src/tree_menu_app &&
      python3 manage.py migrate &&
      ./start_app.sh'
    depends_on:
      - db

volumes:
  pg_data:
    driver: local
